name: Upload to Supabase Storage

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
# We can save the environment variables/secrets in the Github Repo (Settings -> Secrets and variables)
    env:
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

    steps:
#Step-1: Using a Supabase loader from the Github Marketplace
    - uses: actions/checkout@v3
#Step-2: Loading data from local to S3 - Trigger based on New Pushes to repository
    - uses: brendenehlers/supabase-storage-upload@v1
      id: test-action
      with:
        repo_directory: ${{ github.workspace }}
        upload_directory_path: 'data'
        bucket_name: 'S3'
#Step-3: Printing S3 load success message
    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.message }}"